### ISSUE TITLE
Publish the sdk

### ISSUE THREAD

**Issue by pasviegas** [bronto/bronto-api-java-sdk#24]
Hey guys! Please consider publishing the sdk.

You can publish to maven central or even bintray, as your repo is open.

Thanks!

**Comment by mbaumbach** [comment]
@pasviegas Thanks for the feedback. We're now published on Maven Central, however we did modify the dependency groupId. This should be the dependency you use going forward:

```xml
<dependency>
    <groupId>com.bronto.api</groupId>
    <artifactId>bronto-api-sdk</artifactId>
    <version>1.0.5</version>
</dependency>
```

**Comment by pasviegas** [comment]
Hey! Thanks a lot :)
